(function(){
  'use strict';
  const LOGIC=window.RACE_LOGIC,SAVE_KEY='underground-racing-save-v1',$=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)],money=value=>'$'+Math.round(Number(value)||0).toLocaleString();
  const characters=[
    {id:'betty',name:'Betty',tag:'THE RAILBIRD',asset:'assets/characters/betty.webp',bio:'Blue hair, red visor, forty years of remembering which favorite folded in the mud.'},
    {id:'bruce',name:'Bruce',tag:'THE NUMBERS MAN',asset:'assets/characters/bruce.webp',bio:'Keeps a pencil behind his ear and trusts a clean form line more than a hot tip.'},
    {id:'carl',name:'Carl',tag:'THE HUSTLER',asset:'assets/characters/carl.webp',bio:'Slick hair, thin mustache, and absolute confidence whenever the long shot looks live.'}
  ];
  const conditions=[
    {id:'fast',name:'FAST',pace:'speed',color:'#d3a143',track:'#334326',note:'Dry and firm. Early speed and a clean break carry extra weight.'},
    {id:'good',name:'GOOD',pace:'balanced',color:'#83b66d',track:'#32402c',note:'A fair surface with a little give. Balanced runners get their honest chance.'},
    {id:'muddy',name:'MUDDY',pace:'stamina',color:'#b3814d',track:'#4b3522',note:'Wet, deep footing. Stamina, composure, and proven mud form matter more.'},
    {id:'sloppy',name:'SLOPPY',pace:'stamina',color:'#63a4bd',track:'#34464b',note:'Standing water and kickback. Specialists rise; volatile runners get even harder to trust.'}
  ];
  const originalHorseNames=['Midnight Bell','Southpaw Sally','Neon Thunder','Iron Hoof','Desert Ghost','Final Round','Blue Corner','Knockout Rose','Long Count','Main Event','Phoenix Fire','Cage Rattler','Velvet Hammer','Sunday Static','Copper Wire','Borrowed Time','Dead Heat','Whiskey River','Pocket Ace','Cold Shoulder','Lucky Receipt','Backstretch Betty','Paper Crown','No Refunds','Quiet Riot','Red Lantern','Photo Finish','Loose Change','Second Wind','Night Clerk','Hard Eight','Velvet Rope','Smoke Signal','Track Phantom','Gold Teeth','Last Call'];
  const horseLeads=['Afterhours','American','Bourbon','Broken','Chrome','Copper','Crimson','Desert','Fast','Golden','Hard','Last','Lucky','Midnight','Neon','Paper','Phoenix','Quiet','Red','River','Silver','Southpaw','Sunday','Velvet','Wild'],horseTails=['Ace','Bell','Crown','Dream','Echo','Fire','Ghost','Hammer','Heat','Hoof','Lightning','Phantom','Receipt','Riot','Rose','Signal','Static','Storm','Thunder','Wire'];
  const horseNames=LOGIC.buildUniqueNames(originalHorseNames,horseLeads,horseTails,200);
  // Reuses Cage Grind's USA and Latin fighter-name pools, formatted as conventional jockey names.
  const trainers=['Mara Voss','Eddie Flint','June Mercer','Cal Knox','Rita Sloan','Tommy Vale','Nina Cross','Walt Dugan','Lenora Pike'],jockeys=['Rafael Garcia','Diego Santos','Carlos Lopez','Mateo Reyes','Javier Diaz','Santiago Morales','Adrian Rivera','Julio Ortiz','Sebastian Vega','Alejandro Perez','Miguel Rodriguez','Luis Fernandez','Andres Torres','Camilo Sanchez','Randy Jones','Aaron Carter','Caleb Brooks','Marcus Davis','Damon Reed','Jonah Smith','Cole Anderson','Trent Williams'],colors=['#63d4ff','#ff6b72','#d38cff','#c9d3df','#f2c46d','#67dfaa','#538dff','#ff76bd','#f08c55','#ffe05d','#ff934f','#8ce36f'],styles=['FRONT','CLOSER','VOLATILE','PRESSER'],tripNotes=['Broke sharp; weakened late.','Traffic at the quarter pole.','Wide trip; finished willingly.','Pressed pace; held ground.','Slow start; strong gallop-out.','Saved ground; no room late.','Dueled early; stayed game.','Clear lane; best stride late.'];
  function buildHorseRoster(seed){return horseNames.map((name,index)=>{const random=LOGIC.seededRandom(LOGIC.hashSeed(`${seed}|horse|${name}`)),style=styles[Math.floor(random()*styles.length)],speed=4+Math.floor(random()*7),stamina=4+Math.floor(random()*7),breaking=4+Math.floor(random()*7),consistency=4+Math.floor(random()*7),favored=['fast','good','muddy','sloppy'][Math.floor(random()*4)],conditionBias={fast:0,good:0,muddy:0,sloppy:0};conditionBias[favored]=2;conditionBias[style==='FRONT'?'fast':style==='CLOSER'?'muddy':'good']+=1;return {id:`horse-${String(index+1).padStart(3,'0')}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name,style,clue:tripNotes[Math.floor(random()*tripNotes.length)],age:2+Math.floor(random()*8),sex:['C','G','M','F'][Math.floor(random()*4)],color:colors[Math.floor(random()*colors.length)],trainer:trainers[Math.floor(random()*trainers.length)],jockey:jockeys[Math.floor(random()*jockeys.length)],weight:110+Math.floor(random()*17),starts:0,wins:0,places:0,shows:0,earnings:0,earningsPerStart:0,speedFigure:48+Math.floor(random()*59),topSpeedFigure:0,classRating:50+Math.floor(random()*71),earlyPace:35+Math.floor(random()*86),latePace:35+Math.floor(random()*86),workoutSeconds:Number((46+random()*7).toFixed(1)),workoutPosition:1+Math.floor(random()*18),workoutField:18+Math.floor(random()*13),speed,stamina,break:breaking,consistency,form:[],recentRaces:[],distancePref:random()<.24?'route':random()<.35?'versatile':'sprint',surfacePref:'dirt',equipment:index%6===0?'BLINKERS':index%7===0?'SHADOW ROLL':'NONE',medication:index%4===0?'L':'—',wetStarts:0,wetWins:0,conditionBias}})}
  const betDefinitions={
    win:{label:'WIN',help:'Your horse must finish first.',picks:1},place:{label:'PLACE',help:'Your horse can finish first or second.',picks:1},show:{label:'SHOW',help:'Your horse can finish first, second, or third.',picks:1},atb:{label:'ACROSS BOARD',help:'Three separate bets—Win, Place, and Show—on one horse.',picks:1},exacta:{label:'EXACTA',help:'Pick first and second in the exact order.',picks:2},exactaBox:{label:'EXACTA BOX',help:'Pick two horses to finish first and second in either order.',picks:2}
  };
  const defaults={version:5,characterId:'',wallet:500,raceNumber:1,seed:Date.now(),history:[],activeRace:null,roster:[],worldDay:0,pendingTicket:null,raceCompleted:false};
  let state=load(),betType='win',stake=2,picks=[],race=null,racing=false;

  function load(){try{const parsed=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!parsed||typeof parsed!=='object')return {...defaults};const current=parsed.version===defaults.version&&Array.isArray(parsed.roster)&&parsed.roster.length===200;return {...defaults,...parsed,version:defaults.version,wallet:Math.max(0,Math.round(Number(parsed.wallet)||0)),raceNumber:Math.max(1,Math.floor(Number(parsed.raceNumber)||1)),history:Array.isArray(parsed.history)?parsed.history.slice(0,12):[],roster:current?parsed.roster:[],worldDay:current?Math.max(0,Math.floor(Number(parsed.worldDay)||0)):0,activeRace:current?parsed.activeRace:null}}catch{return {...defaults}}}
  function save(){state.activeRace=race;localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
  function selectedCharacter(){return characters.find(character=>character.id===state.characterId)}
  function ensureWorld(){if(state.roster.length===200)return;state.roster=LOGIC.seedWorld(buildHorseRoster(state.seed),conditions,LOGIC.hashSeed(`${state.seed}|history`),5);state.worldDay=0;state.activeRace=null}
  function ensureRace(){ensureWorld();if(state.raceCompleted){state.raceNumber++;state.activeRace=null;state.raceCompleted=false}if(state.activeRace?.field?.length&&state.activeRace?.condition)race=state.activeRace;else{state.pendingTicket=null;race=LOGIC.buildRace(state.roster,conditions,LOGIC.hashSeed(`${state.seed}|${state.raceNumber}`));save()}}

  function renderCharacters(){$('#characterGrid').innerHTML=characters.map(character=>`<button class="character-card" type="button" data-character="${character.id}"><img src="${character.asset}" alt="${character.name}, ${character.tag.toLowerCase()}"><span class="character-copy"><small>${character.tag}</small><b>${character.name.toUpperCase()}</b><span>${character.bio}</span><em>PLAY AS ${character.name.toUpperCase()} →</em></span></button>`).join('')}
  function chooseCharacter(id){if(!characters.some(character=>character.id===id))return;state.characterId=id;save();showGame()}
  function showGame(){const character=selectedCharacter();if(!character)return;$('#onboardingScreen').classList.remove('active');$('#raceScreen').classList.add('active');$('#playerAvatar').src=character.asset;$('#playerAvatar').alt=character.name;$('#playerTag').textContent=character.tag;$('#playerName').textContent=character.name.toUpperCase();$('#playerBio').textContent=character.bio;ensureRace();renderAll();if(state.pendingTicket)settleInterruptedRace()}
  function fitMeter(fit){const filled=Math.round(fit/20);return `<span class="fit" aria-label="Track fit ${fit} out of 100">${[1,2,3,4,5].map(index=>`<i class="${index<=filled?'on':''}"></i>`).join('')}</span>`}
  function renderHorses(){$('#horseList').innerHTML=race.field.map(horse=>`<button class="horse-card ${picks.includes(horse.id)?'selected':''}" type="button" data-horse="${horse.id}" role="listitem" aria-pressed="${picks.includes(horse.id)}" style="--silk:${horse.color}"><span class="silk">${horse.program}</span><span><span class="horse-name"><b>${horse.name}</b><em>${horse.age}${horse.sex} · ${horse.style}</em></span><span class="horse-meta">ESF ${horse.speedFigure} <i>(TOP ${horse.topSpeedFigure})</i> · CLASS ${horse.classRating} · ${horse.weight} LB<br>J ${horse.jockey} · T ${horse.trainer} · ${horse.wins}-${horse.places}-${horse.shows} FROM ${horse.starts}<br><span class="form">LAST 5 ${horse.form.join('-')}</span> · $${horse.earningsPerStart.toLocaleString()}/START · FIT ${horse.fit}% ${fitMeter(horse.fit)}<br>WORK ${horse.workoutSeconds}s (${horse.workoutPosition}/${horse.workoutField}) · ${horse.equipment} · MED ${horse.medication} · WET ${horse.wetWins}/${horse.wetStarts}</span></span><span class="horse-odds"><b>${horse.odds}/1</b><small>MORNING LINE</small></span></button>`).join('')}
  function pickHorse(id){if(racing)return;const needed=betDefinitions[betType].picks;if(needed===1)picks=[id];else if(picks.includes(id))picks=picks.filter(item=>item!==id);else picks=[...picks,id].slice(-2);renderHorses();renderTicket()}
  function renderBetTypes(){$('#betTypes').innerHTML=Object.entries(betDefinitions).map(([id,definition])=>`<button type="button" data-bet-type="${id}" class="${id===betType?'active':''}" aria-pressed="${id===betType}">${definition.label}</button>`).join('')}
  function chooseBetType(type){if(!betDefinitions[type]||racing)return;betType=type;picks=[];renderBetTypes();renderHorses();renderTicket()}
  function renderTicket(){const definition=betDefinitions[betType],chosen=picks.map((id,index)=>{const horse=race.field.find(item=>item.id===id);return horse?`${definition.picks===2?`${index+1}${index===0?'ST':'ND'} · `:''}#${horse.program} ${horse.name}`:''}).filter(Boolean);$('#ticketHelp').textContent=definition.help;$('#ticketPicks').innerHTML=chosen.length?chosen.map(text=>`<b>${text}</b>`).join('<br>'):`${definition.picks===2?'SELECT TWO HORSES':'SELECT A HORSE'} FROM THE PROGRAM`;const cost=LOGIC.ticketCost(betType,stake);$('#ticketCost').textContent=money(cost);$('#ticketSummary').textContent=`${definition.label} · $${stake} BASE${betType==='atb'?' × 3 BETS':betType==='exactaBox'?' × 2 COMBINATIONS':''}`;const validation=LOGIC.validateTicket({type:betType,stake,picks,wallet:state.wallet,field:race.field});$('#placeBet').disabled=!validation.ok||racing;$('#ticketMessage').textContent=validation.ok?'TICKET READY':validation.reason;$$('[data-stake]').forEach(button=>button.classList.toggle('active',Number(button.dataset.stake)===stake))}
  function renderHistory(){const list=$('#historyList');list.innerHTML=state.history.length?state.history.map(item=>`<div class="history-row"><span>RACE ${item.race}</span><span>${item.type} · ${item.picks}</span><b class="${item.profit>=0?'win':'loss'}">${item.profit>=0?'+':''}${money(item.profit)}</b></div>`).join(''):'<div class="empty">NO TICKETS YET. THE WINDOW IS OPEN.</div>'}
  function renderAll(){const condition=race.condition;document.documentElement.style.setProperty('--condition',condition.color);document.documentElement.style.setProperty('--track',condition.track);$('#walletValue').textContent=money(state.wallet);$('#raceNumber').textContent=state.raceNumber;$('#ticketRace').textContent=state.raceNumber;$('#conditionBadge').innerHTML=`<small>${condition.distance} · CLASS ${condition.raceClass}</small><b>${condition.name} DIRT</b><span>${condition.pace==='speed'?'SPEED-FAVORING':condition.pace==='stamina'?'STAMINA-FAVORING':'BALANCED'}</span>`;$('#conditionNote').textContent=`${condition.note} Last 5 and career records come from completed races across the 200-horse circuit.`;renderBetTypes();renderHorses();renderTicket();renderHistory()}
  function runnerLane(horse,progress=4){return `<div class="lane" style="--silk:${horse.color}"><span class="lane-num">${horse.program}</span><span class="rail"><img class="runner" data-runner="${horse.id}" src="assets/horses/racehorse-right.png" alt="${horse.name}" style="--progress:${progress}"><i class="finish-line" aria-hidden="true"></i></span></div>`}
  function placeBet(){const validation=LOGIC.validateTicket({type:betType,stake,picks,wallet:state.wallet,field:race.field});if(!validation.ok){$('#ticketMessage').textContent=validation.reason;return}racing=true;state.wallet-=validation.cost;const ticket={type:betType,stake:validation.stake,picks:[...validation.picks],cost:validation.cost},resolution=LOGIC.resolveRace(race.field,race.condition,LOGIC.hashSeed(`${race.seed}|official-result`)),order=resolution.order,finishIndex=new Map(order.map((id,index)=>[id,index]));state.pendingTicket=ticket;$('#walletValue').textContent=money(state.wallet);$('#placeBet').disabled=true;$('#raceStage').hidden=false;$('#resultBoard').hidden=true;$('#nextRace').hidden=true;$('#liveRaceNumber').textContent=state.raceNumber;$('#raceCall').textContent="THEY'RE LOADING THE GATE";$('#track').innerHTML=race.field.map(horse=>runnerLane(horse)).join('');$('#raceStage').scrollIntoView({behavior:'smooth',block:'start'});save();let step=0;const timer=setInterval(()=>{step++;$('#raceCall').textContent=step<3?'THEY ARE OFF!':step<7?'DOWN THE BACKSTRETCH':step<10?'TURNING FOR HOME':'AT THE WIRE!';race.field.forEach(horse=>{const position=finishIndex.get(horse.id),noise=Math.random()*5,base=step*8.5+(race.field.length-position)*.6+noise;const runner=$(`[data-runner="${horse.id}"]`);runner.style.setProperty('--progress',Math.min(step===10?96-position*.55:91,base))});if(step>=10){clearInterval(timer);setTimeout(()=>finishRace(ticket,resolution),700)}},520)}
  function settleInterruptedRace(){const ticket=state.pendingTicket;if(!ticket)return;const resolution=LOGIC.resolveRace(race.field,race.condition,LOGIC.hashSeed(`${race.seed}|official-result`)),positions=new Map(resolution.order.map((id,index)=>[id,index]));$('#raceStage').hidden=false;$('#liveRaceNumber').textContent=state.raceNumber;$('#track').innerHTML=race.field.map(horse=>runnerLane(horse,96-positions.get(horse.id)*.55)).join('');finishRace(ticket,resolution)}
  function finishRace(ticket,resolution){const order=resolution.order,result=LOGIC.settleTicket(ticket,race.field,order),selectedNames=ticket.picks.map(id=>race.field.find(horse=>horse.id===id)?.name).join(' / '),worldDay=state.worldDay+1,winner=race.field.find(horse=>horse.id===order[0]);state.pendingTicket=null;state.raceCompleted=true;state.wallet+=result.payout;state.history.unshift({race:state.raceNumber,type:betDefinitions[ticket.type].label,picks:selectedNames,profit:result.profit});state.history=state.history.slice(0,12);state.roster=LOGIC.applyRaceResult(state.roster,race.field,race.condition,order,`P-${state.raceNumber}`,30000,resolution.details);state.roster=LOGIC.simulateWorldRound(state.roster,conditions,LOGIC.hashSeed(`${state.seed}|world-day|${worldDay}`),{excludeIds:order,raceIdPrefix:`D${worldDay}`});state.worldDay=worldDay;save();$('#walletValue').textContent=money(state.wallet);$('#resultBoard').innerHTML=order.map((id,index)=>{const horse=race.field.find(item=>item.id===id);return `<div class="result-row ${ticket.picks.includes(id)?'ticket-horse':''}"><b>${index+1}</b><span>#${horse.program} ${horse.name}</span><small>${horse.odds}/1</small></div>`}).join('')+`<div class="race-reason"><b>WHY ${winner.name.toUpperCase()} WON</b><span>${resolution.winnerStory.toUpperCase()} · ${resolution.paceScenario.toUpperCase()} PACE</span></div><div class="settlement ${result.won?'win':'loss'}">${result.won?`TICKET CASHES · ${money(result.payout)} RETURN`:`TICKET MISSES · ${money(ticket.cost)} LOST`}</div>`;$('#resultBoard').hidden=false;$('#nextRace').hidden=false;$('#raceCall').textContent=`${winner.name.toUpperCase()} WINS`;racing=false;renderHistory()}
  function nextRace(){state.raceNumber++;state.activeRace=null;state.raceCompleted=false;picks=[];betType='win';stake=2;race=null;ensureRace();$('#raceStage').hidden=true;renderAll();window.scrollTo({top:0,behavior:'smooth'})}
  function resetGame(){if(!confirm('Reset your character, wallet, racing world, and ticket history on this device?'))return;localStorage.removeItem(SAVE_KEY);state={...defaults,seed:Date.now(),history:[],roster:[]};race=null;picks=[];betType='win';stake=2;$('#raceScreen').classList.remove('active');$('#onboardingScreen').classList.add('active');window.scrollTo(0,0)}

  renderCharacters();
  $('#characterGrid').addEventListener('click',event=>{const button=event.target.closest('[data-character]');if(button)chooseCharacter(button.dataset.character)});
  $('#horseList').addEventListener('click',event=>{const button=event.target.closest('[data-horse]');if(button)pickHorse(button.dataset.horse)});
  $('#betTypes').addEventListener('click',event=>{const button=event.target.closest('[data-bet-type]');if(button)chooseBetType(button.dataset.betType)});
  $('#stakeButtons').addEventListener('click',event=>{const button=event.target.closest('[data-stake]');if(!button)return;stake=Number(button.dataset.stake);$('#stakeInput').value=stake;renderTicket()});
  $('#stakeInput').addEventListener('input',event=>{stake=Math.max(0,Math.floor(Number(event.target.value)||0));renderTicket()});
  $('#placeBet').addEventListener('click',placeBet);$('#nextRace').addEventListener('click',nextRace);$('#resetGame').addEventListener('click',resetGame);$('#howToPlay').addEventListener('click',()=>$('#guideDialog').showModal());$('#closeGuide').addEventListener('click',()=>$('#guideDialog').close());
  if(selectedCharacter())showGame();
})();
