(function(){
  'use strict';
  const LOGIC=window.RACE_LOGIC,SAVE_KEY='underground-racing-save-v1',$=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)],money=value=>'$'+Math.round(Number(value)||0).toLocaleString();
  const characters=[
    {id:'betty',name:'Betty',tag:'THE RAILBIRD',asset:'assets/characters/betty.webp',bio:'Blue hair, red visor, forty years of remembering which favorite folded in the mud.'},
    {id:'bruce',name:'Bruce',tag:'THE NUMBERS MAN',asset:'assets/characters/bruce.webp',bio:'Keeps a pencil behind his ear and trusts a clean form line more than a hot tip.'},
    {id:'carl',name:'Carl',tag:'THE HUSTLER',asset:'assets/characters/carl.webp',bio:'Slick hair, thin mustache, and absolute confidence whenever the long shot looks live.'}
  ];
  const conditions=[
    {id:'fast',name:'FAST',pace:'speed',color:'#d3a143',track:'#334326',note:'Dry and firm. Early speed and a clean break carry extra weight.'},
    {id:'good',name:'GOOD',pace:'balanced',color:'#83b66d',track:'#32402c',note:'A fair surface with a little give. Balanced runners get their honest chance.'},
    {id:'muddy',name:'MUDDY',pace:'stamina',color:'#b3814d',track:'#4b3522',note:'Wet, deep footing. Stamina, composure, and proven mud form matter more.'},
    {id:'sloppy',name:'SLOPPY',pace:'stamina',color:'#63a4bd',track:'#34464b',note:'Standing water and kickback. Specialists rise; volatile runners get even harder to trust.'}
  ];
  const horseNames=['Midnight Bell','Southpaw Sally','Neon Thunder','Iron Hoof','Desert Ghost','Final Round','Blue Corner','Knockout Rose','Long Count','Main Event','Phoenix Fire','Cage Rattler','Velvet Hammer','Sunday Static','Copper Wire','Borrowed Time','Dead Heat','Whiskey River','Pocket Ace','Cold Shoulder','Lucky Receipt','Backstretch Betty','Paper Crown','No Refunds','Quiet Riot','Red Lantern','Photo Finish','Loose Change','Second Wind','Night Clerk','Hard Eight','Velvet Rope','Smoke Signal','Track Phantom','Gold Teeth','Last Call'];
  const trainers=['Mara Voss','Eddie Flint','June Mercer','Cal Knox','Rita Sloan','Tommy Vale','Nina Cross','Walt Dugan','Lenora Pike'],jockeys=['I. Vega','M. Rios','T. Bell','S. Cole','A. Quinn','J. Cruz','R. Lane','D. Price','K. Moss','P. Hart'],colors=['#63d4ff','#ff6b72','#d38cff','#c9d3df','#f2c46d','#67dfaa','#538dff','#ff76bd','#f08c55','#ffe05d','#ff934f','#8ce36f'],styles=['FRONT','CLOSER','VOLATILE','PRESSER'],tripNotes=['Broke sharp; weakened late.','Traffic at the quarter pole.','Wide trip; finished willingly.','Pressed pace; held ground.','Slow start; strong gallop-out.','Saved ground; no room late.','Dueled early; stayed game.','Clear lane; best stride late.'];
  const horses=horseNames.map((name,index)=>{const style=styles[index%styles.length],speed=6+(index*3)%5,stamina=5+(index*7)%6,breaking=4+(index*5)%7,consistency=4+(index*2)%7,starts=1+(index*17)%55,wins=Math.floor(starts*(.08+(index%5)*.045)),places=Math.floor(starts*(.09+(index%4)*.03)),shows=Math.floor(starts*(.08+(index%3)*.035)),speedFigure=35+(index*17)%86,conditionBias=style==='FRONT'?{fast:2,good:1,muddy:-1,sloppy:-2}:style==='CLOSER'?{fast:-1,good:1,muddy:2,sloppy:2}:style==='PRESSER'?{fast:0,good:2,muddy:1,sloppy:0}:{fast:1,good:0,muddy:-1,sloppy:2};return {id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,style,clue:tripNotes[index%tripNotes.length],age:2+index%8,sex:['C','G','M','F'][index%4],color:colors[index%colors.length],trainer:trainers[(index*2)%trainers.length],jockey:jockeys[(index*3)%jockeys.length],weight:110+(index*7)%17,starts,wins,places,shows,earningsPerStart:(index*1901)%25001,speedFigure,topSpeedFigure:Math.min(120,speedFigure+3+index%12),classRating:50+(index*13)%71,earlyPace:35+(index*19)%86,latePace:35+(index*23)%86,workoutSeconds:Number((46+(index*7)%71/10).toFixed(1)),workoutPosition:1+(index*5)%18,workoutField:18+(index%13),speed,stamina,break:breaking,consistency,form:[1+(index*3)%12,1+(index*5)%12,1+(index*7)%12],distancePref:index%5===0?'route':index%3===0?'versatile':'sprint',surfacePref:'dirt',equipment:index%6===0?'BLINKERS':index%7===0?'SHADOW ROLL':'NONE',medication:index%4===0?'L':'—',wetStarts:2+index%9,wetWins:index%4,conditionBias}});
  const betDefinitions={
    win:{label:'WIN',help:'Your horse must finish first.',picks:1},place:{label:'PLACE',help:'Your horse can finish first or second.',picks:1},show:{label:'SHOW',help:'Your horse can finish first, second, or third.',picks:1},atb:{label:'ACROSS BOARD',help:'Three separate bets—Win, Place, and Show—on one horse.',picks:1},exacta:{label:'EXACTA',help:'Pick first and second in the exact order.',picks:2},exactaBox:{label:'EXACTA BOX',help:'Pick two horses to finish first and second in either order.',picks:2}
  };
  const defaults={version:1,characterId:'',wallet:500,raceNumber:1,seed:Date.now(),history:[],activeRace:null};
  let state=load(),betType='win',stake=2,picks=[],race=null,racing=false;

  function load(){try{const parsed=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(!parsed||typeof parsed!=='object')return {...defaults};return {...defaults,...parsed,wallet:Math.max(0,Math.round(Number(parsed.wallet)||0)),raceNumber:Math.max(1,Math.floor(Number(parsed.raceNumber)||1)),history:Array.isArray(parsed.history)?parsed.history.slice(0,12):[]}}catch{return {...defaults}}}
  function save(){state.activeRace=race;localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
  function selectedCharacter(){return characters.find(character=>character.id===state.characterId)}
  function ensureRace(){if(state.activeRace?.field?.length&&state.activeRace?.condition)race=state.activeRace;else{race=LOGIC.buildRace(horses,conditions,LOGIC.hashSeed(`${state.seed}|${state.raceNumber}`));save()}}

  function renderCharacters(){$('#characterGrid').innerHTML=characters.map(character=>`<button class="character-card" type="button" data-character="${character.id}"><img src="${character.asset}" alt="${character.name}, ${character.tag.toLowerCase()}"><span class="character-copy"><small>${character.tag}</small><b>${character.name.toUpperCase()}</b><span>${character.bio}</span><em>PLAY AS ${character.name.toUpperCase()} →</em></span></button>`).join('')}
  function chooseCharacter(id){if(!characters.some(character=>character.id===id))return;state.characterId=id;save();showGame()}
  function showGame(){const character=selectedCharacter();if(!character)return;$('#onboardingScreen').classList.remove('active');$('#raceScreen').classList.add('active');$('#playerAvatar').src=character.asset;$('#playerAvatar').alt=character.name;$('#playerTag').textContent=character.tag;$('#playerName').textContent=character.name.toUpperCase();$('#playerBio').textContent=character.bio;ensureRace();renderAll()}
  function fitMeter(fit){const filled=Math.round(fit/20);return `<span class="fit" aria-label="Track fit ${fit} out of 100">${[1,2,3,4,5].map(index=>`<i class="${index<=filled?'on':''}"></i>`).join('')}</span>`}
  function renderHorses(){$('#horseList').innerHTML=race.field.map(horse=>`<button class="horse-card ${picks.includes(horse.id)?'selected':''}" type="button" data-horse="${horse.id}" role="listitem" aria-pressed="${picks.includes(horse.id)}" style="--silk:${horse.color}"><span class="silk">${horse.program}</span><span><span class="horse-name"><b>${horse.name}</b><em>${horse.age}${horse.sex} · ${horse.style}</em></span><span class="horse-meta">ESF ${horse.speedFigure} <i>(TOP ${horse.topSpeedFigure})</i> · CLASS ${horse.classRating} · ${horse.weight} LB<br>J ${horse.jockey} · T ${horse.trainer} · ${horse.wins}-${horse.places}-${horse.shows} FROM ${horse.starts}<br><span class="form">FORM ${horse.form.join('-')}</span> · FIT ${horse.fit}% ${fitMeter(horse.fit)} · WORK ${horse.workoutSeconds}s (${horse.workoutPosition}/${horse.workoutField})<br>${horse.equipment} · MED ${horse.medication} · WET ${horse.wetWins}/${horse.wetStarts} · ${horse.clue}</span></span><span class="horse-odds"><b>${horse.odds}/1</b><small>MORNING LINE</small></span></button>`).join('')}
  function pickHorse(id){if(racing)return;const needed=betDefinitions[betType].picks;if(needed===1)picks=[id];else if(picks.includes(id))picks=picks.filter(item=>item!==id);else picks=[...picks,id].slice(-2);renderHorses();renderTicket()}
  function renderBetTypes(){$('#betTypes').innerHTML=Object.entries(betDefinitions).map(([id,definition])=>`<button type="button" data-bet-type="${id}" class="${id===betType?'active':''}" aria-pressed="${id===betType}">${definition.label}</button>`).join('')}
  function chooseBetType(type){if(!betDefinitions[type]||racing)return;betType=type;picks=[];renderBetTypes();renderHorses();renderTicket()}
  function renderTicket(){const definition=betDefinitions[betType],chosen=picks.map((id,index)=>{const horse=race.field.find(item=>item.id===id);return horse?`${definition.picks===2?`${index+1}${index===0?'ST':'ND'} · `:''}#${horse.program} ${horse.name}`:''}).filter(Boolean);$('#ticketHelp').textContent=definition.help;$('#ticketPicks').innerHTML=chosen.length?chosen.map(text=>`<b>${text}</b>`).join('<br>'):`${definition.picks===2?'SELECT TWO HORSES':'SELECT A HORSE'} FROM THE PROGRAM`;const cost=LOGIC.ticketCost(betType,stake);$('#ticketCost').textContent=money(cost);$('#ticketSummary').textContent=`${definition.label} · $${stake} BASE${betType==='atb'?' × 3 BETS':betType==='exactaBox'?' × 2 COMBINATIONS':''}`;const validation=LOGIC.validateTicket({type:betType,stake,picks,wallet:state.wallet,field:race.field});$('#placeBet').disabled=!validation.ok||racing;$('#ticketMessage').textContent=validation.ok?'TICKET READY':validation.reason;$$('[data-stake]').forEach(button=>button.classList.toggle('active',Number(button.dataset.stake)===stake))}
  function renderHistory(){const list=$('#historyList');list.innerHTML=state.history.length?state.history.map(item=>`<div class="history-row"><span>RACE ${item.race}</span><span>${item.type} · ${item.picks}</span><b class="${item.profit>=0?'win':'loss'}">${item.profit>=0?'+':''}${money(item.profit)}</b></div>`).join(''):'<div class="empty">NO TICKETS YET. THE WINDOW IS OPEN.</div>'}
  function renderAll(){const condition=race.condition;document.documentElement.style.setProperty('--condition',condition.color);document.documentElement.style.setProperty('--track',condition.track);$('#walletValue').textContent=money(state.wallet);$('#raceNumber').textContent=state.raceNumber;$('#ticketRace').textContent=state.raceNumber;$('#conditionBadge').innerHTML=`<small>${condition.distance} · CLASS ${condition.raceClass}</small><b>${condition.name} DIRT</b><span>${condition.pace==='speed'?'SPEED-FAVORING':condition.pace==='stamina'?'STAMINA-FAVORING':'BALANCED'}</span>`;$('#conditionNote').textContent=condition.note;renderBetTypes();renderHorses();renderTicket();renderHistory()}
  function runnerLane(horse,progress=4){return `<div class="lane" style="--silk:${horse.color}"><span class="lane-num">${horse.program}</span><span class="rail"><img class="runner" data-runner="${horse.id}" src="assets/horses/racehorse-right.png" alt="${horse.name}" style="--progress:${progress}"><i class="finish-line" aria-hidden="true"></i></span></div>`}
  function placeBet(){const validation=LOGIC.validateTicket({type:betType,stake,picks,wallet:state.wallet,field:race.field});if(!validation.ok){$('#ticketMessage').textContent=validation.reason;return}racing=true;state.wallet-=validation.cost;const ticket={type:betType,stake:validation.stake,picks:validation.picks,cost:validation.cost};$('#walletValue').textContent=money(state.wallet);$('#placeBet').disabled=true;$('#raceStage').hidden=false;$('#resultBoard').hidden=true;$('#nextRace').hidden=true;$('#liveRaceNumber').textContent=state.raceNumber;$('#raceCall').textContent="THEY'RE LOADING THE GATE";$('#track').innerHTML=race.field.map(horse=>runnerLane(horse)).join('');$('#raceStage').scrollIntoView({behavior:'smooth',block:'start'});const rolls=race.field.map(()=>Math.random()),order=LOGIC.finishRace(race.field,race.condition,rolls),finishIndex=new Map(order.map((id,index)=>[id,index]));save();let step=0;const timer=setInterval(()=>{step++;$('#raceCall').textContent=step<3?'THEY ARE OFF!':step<7?'DOWN THE BACKSTRETCH':step<10?'TURNING FOR HOME':'AT THE WIRE!';race.field.forEach(horse=>{const position=finishIndex.get(horse.id),noise=Math.random()*5,base=step*8.5+(race.field.length-position)*.6+noise;const runner=$(`[data-runner="${horse.id}"]`);runner.style.setProperty('--progress',Math.min(step===10?96-position*.55:91,base))});if(step>=10){clearInterval(timer);setTimeout(()=>finishRace(ticket,order),700)}},520)}
  function finishRace(ticket,order){const result=LOGIC.settleTicket(ticket,race.field,order),selectedNames=ticket.picks.map(id=>race.field.find(horse=>horse.id===id)?.name).join(' / ');state.wallet+=result.payout;state.history.unshift({race:state.raceNumber,type:betDefinitions[ticket.type].label,picks:selectedNames,profit:result.profit});state.history=state.history.slice(0,12);save();$('#walletValue').textContent=money(state.wallet);$('#resultBoard').innerHTML=order.map((id,index)=>{const horse=race.field.find(item=>item.id===id);return `<div class="result-row ${ticket.picks.includes(id)?'ticket-horse':''}"><b>${index+1}</b><span>#${horse.program} ${horse.name}</span><small>${horse.odds}/1</small></div>`}).join('')+`<div class="settlement ${result.won?'win':'loss'}">${result.won?`TICKET CASHES · ${money(result.payout)} RETURN`:`TICKET MISSES · ${money(ticket.cost)} LOST`}</div>`;$('#resultBoard').hidden=false;$('#nextRace').hidden=false;$('#raceCall').textContent=`${race.field.find(horse=>horse.id===order[0]).name.toUpperCase()} WINS`;racing=false;renderHistory()}
  function nextRace(){state.raceNumber++;state.activeRace=null;picks=[];betType='win';stake=2;race=null;ensureRace();$('#raceStage').hidden=true;renderAll();window.scrollTo({top:0,behavior:'smooth'})}
  function resetGame(){if(!confirm('Reset your character, wallet, and ticket history on this device?'))return;localStorage.removeItem(SAVE_KEY);state={...defaults,seed:Date.now(),history:[]};race=null;picks=[];betType='win';stake=2;$('#raceScreen').classList.remove('active');$('#onboardingScreen').classList.add('active');window.scrollTo(0,0)}

  renderCharacters();
  $('#characterGrid').addEventListener('click',event=>{const button=event.target.closest('[data-character]');if(button)chooseCharacter(button.dataset.character)});
  $('#horseList').addEventListener('click',event=>{const button=event.target.closest('[data-horse]');if(button)pickHorse(button.dataset.horse)});
  $('#betTypes').addEventListener('click',event=>{const button=event.target.closest('[data-bet-type]');if(button)chooseBetType(button.dataset.betType)});
  $('#stakeButtons').addEventListener('click',event=>{const button=event.target.closest('[data-stake]');if(!button)return;stake=Number(button.dataset.stake);$('#stakeInput').value=stake;renderTicket()});
  $('#stakeInput').addEventListener('input',event=>{stake=Math.max(0,Math.floor(Number(event.target.value)||0));renderTicket()});
  $('#placeBet').addEventListener('click',placeBet);$('#nextRace').addEventListener('click',nextRace);$('#resetGame').addEventListener('click',resetGame);$('#howToPlay').addEventListener('click',()=>$('#guideDialog').showModal());$('#closeGuide').addEventListener('click',()=>$('#guideDialog').close());
  if(selectedCharacter())showGame();
})();
